### ISSUE TITLE
na_elementsw_info: Error calling module with LDAP user

### ISSUE THREAD

**Issue by dlenkov** [ansible-collections/netapp.elementsw#9]
### Summary

When trying to use the na_elementsw_info module with LDAP user, an error is encountered. The same test works fine when using local user. The issue is that the module tries to query both the node endpoint on port 442, as well as the cluster endpoint on port 443. However, the node endpoint doesn't currently allow to authenticate properly the LDAP user - it only works with local user. Due to this, the module fails during its initial try to query the node endpoint on port 442. Details below.

The issue is caused by:
https://github.com/ansible-collections/netapp.elementsw/blob/main/plugins/modules/na_elementsw_info.py#L144

By doing the following changes to prevent calling the node endpoint, the module works with LDAP credentials, but obviously with the limitation that node info is not collected:

1/
In https://github.com/ansible-collections/netapp.elementsw/blob/main/plugins/modules/na_elementsw_info.py#L144
From:
`for role, port in [('node', 442), ('cluster', 443)]:`
To:
`for role, port in [('cluster', 443)]:`

2/
In https://github.com/ansible-collections/netapp.elementsw/blob/main/plugins/modules/na_elementsw_info.py#L162-L164
Comment out these 3 lines

3/
In https://github.com/ansible-collections/netapp.elementsw/blob/main/plugins/modules/na_elementsw_info.py#L171-L172
Comment out these 2 lines and replace them with:
`self.methods = dict(self.cluster_methods)`

As per NetApp support ticket 2009210630, as per the engineer who worked on the ticket:
"(...) it seems to be an issue other customer have noticed as well.
From what I understand, it is being looked at for future Element versions."

### Component Name

na_elementsw_info

### Ansible Version

```console
$ ansible --version

Currently testing with:
ansible 2.9.13

However, the error is unrelated to the Ansible version.
```

### ElementSW Collection Version

```console
$ ansible-galaxy collection list

Using netapp.elementsw collection version 21.7.0
```

### Playbook

```console
- name: get all available subsets
  na_elementsw_info:
    hostname: "{{ elementsw_mvip }}"
    username: "{{ elementsw_username }}"
    password: "{{ elementsw_password }}"
    gather_subsets: all
  register: result
  delegate_to: localhost
```

### Steps to Reproduce

When trying to run the example task from the module's documentation, encountering an error when using LDAP user.
The LDAP is granted all permissions from the UI (effectively administrator).

A local user with the same set of privileges, even the same password, is working as expected with the module.

The behavior can also be reproduced by invoking pure API calls to the node & cluster endpoint using "curl" for example.

### Expected Results

The information should be collected from the SFC cluster.

In case the same module should be able to query both node endpoint and cluster endpoint, then it should be made possible to authenticate to the node endpoint using LDAP user in addition to a local user.

If for some reason the above is not feasible, then possibly two separate modules can be made, one for gathering information from the node endpoint (e.g. `na_elementsw_node_info` which would work only with local user), and one gathering information from the cluster endpoint (e.g. `na_elementsw_cluster_info` which would work only with both LDAP user and local user).

### Actual Results

```console
TASK [test_role : get all available subsets] *******************************************************************************************************************
fatal: [server01]: FAILED! => {"changed": false, "msg": " Make sure to use valid node credentials for username and password.Node reported: ApiConnectionError('Bad Credentials')"}
```

**Comment by dlenkov** [comment]
Will appreciate any feedback from repo owners, just to understand the intentions for developing this module further? I don't mind doing a PR with a code fix, but since the most adequate fix (from my perspective at least) is to just make the node endpoint able to work with LDAP credentials, it would make no sense to change the module if this is indeed the plan (in which case, will appreciate any ETA on this API change, even if rough). However, if for some reason this is not planned to happen, then please say so, so possibly we can come up with a workaround, e.g. either splitting the module into 2 modules for node/cluster respectively, or adding a module argument of something like 'node/cluster/all' to determine which endpoints are called, in order to make it functional with LDAP credentials (because right now it is not).

**Comment by lonico** [comment]
We're not doing any active work on this collection.  But if you want to submit a PR, we'll be happy to review it.

I'm not sure why the LDAP authentication is not working for the node.   But we don't have control over the ElementOS APIs.

I would suggest to avoid the calls to `self.module.fail_json` when creating the connections, set self.sfe.node to None, set self.node_methods to {}, and report an error when 'all' or 'all_nodes' is in gather_subsets and self.node_methods is empty.

I think it would require to create self.sfe_error as a dictionary with role as a key to store the error message,

**Comment by dlenkov** [comment]
@lonico Thanks for the feedback.
I'm not 100% sure that this is the same issue, but looking at the 12.5 release notes:
https://library.netapp.com/ecm/ecm_download_file/ECMLP2882193

There's an issue that looks the same at least per the description:

ELEM-16782
When you issue a per-node API call to a
cluster using a Lightweight Directory
Access Protocol (LDAP) account with
administrator access, the call is not
authorized. This issue does not affect
cluster wide API calls using an LDAP
account.

Affected Versions:
12.3 and earlier versions

Interestingly, I'm almost certain that we were experiencing it on v12.5 (which as per the same release notes is the version that comes with the fix), but in any case cannot reproduce anymore on v12.7.
Hence closing this one.
